"""add_payment_links_settlements_and_audit_logs

Revision ID: cd6889a5fff3
Revises: 507422680aae
Create Date: 2026-09-02 11:28:12.415318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd6889a5fff3'
down_revision: Union[str, Sequence[str], None] = '507422680aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_merchant_id'), 'audit_logs', ['merchant_id'], unique=False)
    op.create_table('settlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_settlement_id', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('utr', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processed', 'failed', name='settlement_status'), server_default='pending', nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_settlement_id')
    )
    op.create_index(op.f('ix_settlements_merchant_id'), 'settlements', ['merchant_id'], unique=False)
    op.create_table('payment_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('receipt_number', sa.String(length=100), nullable=True),
    sa.Column('razorpay_link_id', sa.String(length=255), nullable=True),
    sa.Column('razorpay_link_url', sa.Text(), nullable=True),
    sa.Column('callback_url', sa.Text(), nullable=True),
    sa.Column('callback_method', sa.String(length=10), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('created', 'partially_paid', 'paid', 'expired', 'cancelled', name='payment_link_status'), server_default='created', nullable=False),
    sa.Column('notify_sms', sa.Boolean(), nullable=False),
    sa.Column('notify_email', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_link_id')
    )
    op.create_index(op.f('ix_payment_links_merchant_id'), 'payment_links', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_payment_links_order_id'), 'payment_links', ['order_id'], unique=False)
    op.add_column('merchant_profiles', sa.Column('razorpay_key_id', sa.String(length=100), nullable=True))
    op.add_column('merchant_profiles', sa.Column('razorpay_mode', sa.String(length=20), server_default='test', nullable=False))
    op.add_column('merchant_profiles', sa.Column('razorpay_connected_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('merchant_profiles', 'razorpay_key_id_encrypted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant_profiles', sa.Column('razorpay_key_id_encrypted', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('merchant_profiles', 'razorpay_connected_at')
    op.drop_column('merchant_profiles', 'razorpay_mode')
    op.drop_column('merchant_profiles', 'razorpay_key_id')
    op.drop_index(op.f('ix_payment_links_order_id'), table_name='payment_links')
    op.drop_index(op.f('ix_payment_links_merchant_id'), table_name='payment_links')
    op.drop_table('payment_links')
    op.drop_index(op.f('ix_settlements_merchant_id'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_audit_logs_merchant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
