"""add_merchant_timestamps_and_shop_directory_trgm_indexes

Revision ID: e5d489f9680d
Revises: e23c59e5be32
Create Date: 2026-08-31 18:19:51.227299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5d489f9680d'
down_revision: Union[str, Sequence[str], None] = 'e23c59e5be32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_addresses_city_trgm', 'addresses', ['city'], unique=False, postgresql_using='gin', postgresql_ops={'city': 'gin_trgm_ops'})
    op.create_index('ix_addresses_line1_trgm', 'addresses', ['line1'], unique=False, postgresql_using='gin', postgresql_ops={'line1': 'gin_trgm_ops'})
    op.add_column('merchant_profiles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('merchant_profiles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_merchant_profiles_business_type_trgm', 'merchant_profiles', ['business_type'], unique=False, postgresql_using='gin', postgresql_ops={'business_type': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_merchant_profiles_business_type_trgm', table_name='merchant_profiles', postgresql_using='gin', postgresql_ops={'business_type': 'gin_trgm_ops'})
    op.drop_column('merchant_profiles', 'updated_at')
    op.drop_column('merchant_profiles', 'created_at')
    op.drop_index('ix_addresses_line1_trgm', table_name='addresses', postgresql_using='gin', postgresql_ops={'line1': 'gin_trgm_ops'})
    op.drop_index('ix_addresses_city_trgm', table_name='addresses', postgresql_using='gin', postgresql_ops={'city': 'gin_trgm_ops'})
    # ### end Alembic commands ###
