import type { AuditLogEntry } from "../../../types/audit-log/audit";

export const AUDIT_LOG: AuditLogEntry[] = [
  {
    id: "al-01",
    actionType: "Payment Link Created",
    description: "₹500.00 link generated for Rahul Sharma",
    actor: "AI Agent",
    status: "Success",
    timestamp: "2026-08-27T10:12:00",
  },
  {
    id: "al-02",
    actionType: "Payment Link Failed",
    description: "Link generation for Priya Mehta (₹1,200.00) failed — Razorpay test API timeout",
    actor: "AI Agent",
    status: "Failed",
    errorDetail: "Automatically retried after 4s — succeeded on retry, no merchant action needed.",
    timestamp: "2026-08-27T10:13:04",
  },
  {
    id: "al-03",
    actionType: "Payment Link Created",
    description: "₹1,200.00 link generated for Priya Mehta (retry)",
    actor: "AI Agent",
    status: "Success",
    timestamp: "2026-08-27T10:13:08",
  },
  {
    id: "al-04",
    actionType: "Campaign Drafted",
    description: "Diwali offer drafted for 20 customers — awaiting merchant approval",
    actor: "AI Agent",
    status: "Success",
    timestamp: "2026-08-27T09:40:00",
  },
  {
    id: "al-05",
    actionType: "Campaign Approved",
    description: "Diwali offer approved and sent to 20 customers",
    actor: "Merchant",
    status: "Success",
    timestamp: "2026-08-27T09:52:00",
  },
  {
    id: "al-06",
    actionType: "Order Added",
    description: "New order for Ankit Verma — ₹750.00, Diwali festival offer",
    actor: "Merchant",
    status: "Success",
    timestamp: "2026-08-26T18:05:00",
  },
  {
    id: "al-07",
    actionType: "WhatsApp Message Generated",
    description: "Payment reminder generated for Vikram Patel — ₹2,100.00 due",
    actor: "AI Agent",
    status: "Success",
    timestamp: "2026-08-26T17:22:00",
  },
  {
    id: "al-08",
    actionType: "Low Stock Alert",
    description: "Parle-G Biscuit fell below alert threshold (12 units, alert at 15)",
    actor: "System",
    status: "Success",
    timestamp: "2026-08-26T09:00:00",
  },
  {
    id: "al-09",
    actionType: "Customer Message Blocked",
    description: "Outbound message to Meena Iyer blocked — 3-message limit reached without a connection",
    actor: "System",
    status: "Success",
    timestamp: "2026-08-25T14:30:00",
  },
  {
    id: "al-10",
    actionType: "Payout Settled",
    description: "₹8,250.00 settled to HDFC Bank",
    actor: "System",
    status: "Success",
    timestamp: "2026-08-26T08:00:00",
  },
];